# Generated by Django 5.2.7 on 2025-12-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL-идентификатор')),
            ],
            options={
                'verbose_name': 'Категория запчасти',
                'verbose_name_plural': 'Категории запчастей',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='spare_parts.carmake', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'unique_together': {('make', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поколения/модификации')),
                ('year_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год начала выпуска')),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания выпуска')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='spare_parts.carmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Поколение/Модификация',
                'verbose_name_plural': 'Поколения/Модификации',
                'ordering': ('model__make__name', 'model__name', 'year_start'),
            },
        ),
        migrations.CreateModel(
            name='DonorVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_vin', models.CharField(blank=True, help_text="Уникальный ID, например, 'DNR001' или '3'.", max_length=50, null=True, verbose_name='ID Донора/Поступления')),
                ('title', models.CharField(blank=True, help_text="Напр: 'Синий, 2.0л, пробег 140т.км' или 'Поступление #2'", max_length=255, null=True, verbose_name='Название/Описание поступления (для себя)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('production_year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('engine_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Детали двигателя (объем/модель)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полное описание донора')),
                ('transmission_type', models.CharField(blank=True, choices=[('AT', 'Автоматическая'), ('MT', 'Механическая')], max_length=10, null=True, verbose_name='Тип КПП')),
                ('arrival_date', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spare_parts.cargeneration', verbose_name='Модификация (Тип авто)')),
            ],
            options={
                'verbose_name': 'Машина-донор (поступление)',
                'verbose_name_plural': 'Машины-доноры (поступления)',
                'ordering': ['-arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='DonorVehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='donor_vehicle_images/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Внешний URL Изображения')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('donor_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spare_parts.donorvehicle', verbose_name='Машина-донор')),
            ],
            options={
                'verbose_name': 'Изображение донора',
                'verbose_name_plural': 'Изображения донора',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Внутренний артикул продавца')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='OEM/Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('condition', models.CharField(choices=[('used', 'Б/У'), ('new', 'Новая'), ('restored', 'Восстановленная')], default='used', max_length=10, verbose_name='Состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('car_generations', models.ManyToManyField(blank=True, related_name='compatible_parts', to='spare_parts.cargeneration', verbose_name='Совместимые модификации/поколения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spare_parts.category', verbose_name='Категория')),
                ('donor_generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_parts', to='spare_parts.cargeneration', verbose_name='Автомобиль-донор (Поколение/Модификация)')),
                ('donor_vehicle', models.ForeignKey(blank=True, help_text='С какой конкретной машины снята эта запчасть', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='spare_parts.donorvehicle', verbose_name='Конкретная машина-донор (поступление)')),
            ],
            options={
                'verbose_name': 'Запчасть (Объявление)',
                'verbose_name_plural': 'Запчасти (Объявления)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='part_images/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Изображения')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spare_parts.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Изображение запчасти',
                'verbose_name_plural': 'Изображения запчастей',
            },
        ),
        migrations.CreateModel(
            name='PartSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название Подкатегории')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='ЧПУ (Slug)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spare_parts.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория запчасти',
                'verbose_name_plural': 'Подкатегории запчастей',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='spare_parts.partsubcategory', verbose_name='Подкатегория'),
        ),
    ]
