# Generated by Django 5.2.7 on 2025-10-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория запчасти',
                'verbose_name_plural': 'Категории запчастей',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='spare_parts.carmake', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'unique_together': {('make', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поколения/модификации')),
                ('year_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год начала выпуска')),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания выпуска')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='spare_parts.carmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Поколение/Модификация',
                'verbose_name_plural': 'Поколения/Модификации',
                'ordering': ('model__make__name', 'model__name', 'year_start'),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Внутренний артикул продавца')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='OEM/Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('condition', models.CharField(choices=[('used', 'Б/У'), ('new', 'Новая'), ('restored', 'Восстановленная')], default='used', max_length=10, verbose_name='Состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spare_parts.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Запчасть (Объявление)',
                'verbose_name_plural': 'Запчасти (Объявления)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='part_images/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spare_parts.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Изображение запчасти',
                'verbose_name_plural': 'Изображения запчастей',
            },
        ),
    ]
