# Generated by Django 5.2.7 on 2025-10-28 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='car_generations',
            field=models.ManyToManyField(related_name='compatible_parts', to='spare_parts.cargeneration', verbose_name='Совместимые модификации/поколения'),
        ),
        migrations.AddField(
            model_name='part',
            name='donor_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_parts', to='spare_parts.cargeneration', verbose_name='Автомобиль-донор (Поколение/Модификация)'),
        ),
    ]
