# Generated by Django 5.2.7 on 2025-10-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0002_part_car_generations_part_donor_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='car_generations',
            field=models.ManyToManyField(blank=True, related_name='compatible_parts', to='spare_parts.cargeneration', verbose_name='Совместимые модификации/поколения'),
        ),
    ]
