# Generated by Django 5.2.7 on 2025-10-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0003_alter_part_car_generations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='donor_generation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='donor_parts', to='spare_parts.cargeneration', verbose_name='Автомобиль-донор (Поколение/Модификация)'),
            preserve_default=False,
        ),
    ]
