# Generated by Django 5.2.7 on 2025-11-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0004_alter_part_donor_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Напр: 'Синий, 2.0л, пробег 140т.км' или 'Поступление #2'", max_length=255, verbose_name='Название/Описание поступления (для себя)')),
                ('arrival_date', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spare_parts.cargeneration', verbose_name='Модификация (Тип авто)')),
            ],
            options={
                'verbose_name': 'Машина-донор (поступление)',
                'verbose_name_plural': 'Машины-доноры (поступления)',
                'ordering': ['-arrival_date'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='donor_vehicle',
            field=models.ForeignKey(blank=True, help_text='С какой конкретной машины снята эта запчасть', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='spare_parts.donorvehicle', verbose_name='Конкретная машина-донор (поступление)'),
        ),
        migrations.CreateModel(
            name='DonorVehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donor_vehicle_images/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('donor_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spare_parts.donorvehicle', verbose_name='Машина-донор')),
            ],
            options={
                'verbose_name': 'Изображение донора',
                'verbose_name_plural': 'Изображения донора',
            },
        ),
    ]
