# Generated by Django 5.2.7 on 2025-11-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0005_donorvehicle_part_donor_vehicle_donorvehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorvehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='donorvehicle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание донора'),
        ),
        migrations.AddField(
            model_name='donorvehicle',
            name='engine_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Детали двигателя (объем/модель)'),
        ),
        migrations.AddField(
            model_name='donorvehicle',
            name='production_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AddField(
            model_name='donorvehicle',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('AT', 'Автоматическая'), ('MT', 'Механическая')], max_length=10, null=True, verbose_name='Тип КПП'),
        ),
    ]
